source 'https://rubygems.org'

gem 'cucumber'
gem 'ci_reporter', git: 'git://github.com/nicksieger/ci_reporter.git'
gem 'rest-client'
gem 'test-unit'
gem 'vcr'
gem 'webmock'
gem 'minitest'
gem 'rake'
gem 'rspec-expectations'
